apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: user40-k8s
  region: ap-southeast-1

vpc:
  id: "vpc-0d9ad41cadb2935de"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.31.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      ap-southeast-1c:
        id: "subnet-082672b38a831e400"
        cidr: "172.31.0.0/20" # (optional, must match CIDR used by the given subnet)

      ap-southeast-1b:
        id: "subnet-0757ca73698f20204"
        cidr: "172.31.32.0/20"  # (optional, must match CIDR used by the given subnet)

      ap-southeast-1a:
        id: "subnet-0ff019d6b6c47cb4b"
        cidr: "172.31.16.0/20"   # (optional, must match CIDR used by the given subnet)
nodeGroups:
  - name: ng1
    instanceType: m5.xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    volumeType: gp2
    subnets:
      - subnet-082672b38a831e400
      - subnet-0757ca73698f20204
      - subnet-0ff019d6b6c47cb4b
    securityGroups:
      attachIDs: ["sg-07e4330b0dd996d2d"]
    ssh:
      allow: true
      publicKeyName: user40-ap-sea1
      # new feature for restricting SSH access to certain AWS security group IDs
