apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  volumes:             
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc   ## <-- PVC의 이름 설정
  containers:
  - name: ubuntu
    image: ubuntu:16.04
    volumeMounts:       
    - name: pvc
      mountPath: /mnt    ## <-- 컨테이너 상 마운트 경로
    command: ["/usr/bin/tail","-f","/dev/null"]      
